# This is a example blueprint file.

# Docker Image build from binary file.
buildpack:
  image: # Base image.
  binaryFile: # binary file. for example: app.war
  binaryPath: # binary file in container path. for example: /usr/local/tomcat/webapp
  propsFile: # props zip file. for example: props.zip
  startupFile: # startup script file. for example: startup.sh
  startCmd: #start command.
  reloadCmd: #reload command.
     
# Rolling upgrade. 
canary:
  rule: # vcluster/instance/duration. 
  ic 1, 1day # vcluster=ic,instance=1,duration=1day.
  ic 5, 1day # vcluster=ic,instance=5,duration=1day.
  ic 100, 1day  # vcluster=ic, instance=100,duration=1day.
  all dc # all instance.

# Rollback.
rollbak:
  trigger: manual      
