FROM tomcat:8.0

MAINTAIN Admin@dataman-inc.com

ADD sample.zip /usr/local/tomcat/webapps
# DOWNLOAD PROPERTY FILES FROM DISCONF IN BAKER SERVER
COPY  /fileserver/bin/baker /
RUN ./baker disconf pull --path=$CONFIG_DIR && 
./baker disconf unzip --file=props.zip --path=/app &&
mv $CONFIG_DIR /


