# This is a config file for baker.

server: # baker server settings.
  address: "127.0.0.1:8000" # address to listen on.

users: # static users.
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  "test":
    password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123

dockerregistry: # docker registry setting.
    address: "demoregistry.dataman-inc.com"
    repo: "library"
    username: "admin"
    password: "v4kczahOfYqP"
    email: "csd-system@dataman-inc.com"

workpool: # worker pool setting.
   "imagepush":
     size: "1"    


